import {
  FlexibleNavbarBox,
  NavLinkGroups,
  TailwindcssNavbar,
} from "../components/Navbar";
import { NavFooterLayout } from "../components/Layouts";
import { SimpleTextFooter } from "../components/Footer";
import { useRouter } from "next/router";
import Head from "next/head";

const genNavbarItems = (configId: string): NavLinkGroups => [
  {
    groupName: "管理",
    children: [
      {
        name: "服务器",
        link: `/${configId}/servers`,
      },
      {
        name: "规则",
        link: `/${configId}/rules`,
      },
    ],
  },
  {
    groupName: "Clash",
    children: [
      {
        name: "设置",
        link: `/${configId}/clash-general`,
      },
      {
        name: "编辑",
        link: `/${configId}/clash-config-editor`,
      },
    ],
  },
];

type Props = {
  children: React.ReactNode;
};

export const Layout = ({ children }: Props) => {
  const router = useRouter();

  const route = router.route;

  const { pid } = router.query;

  const navbarItems = genNavbarItems(pid as string);

  const navbar = (
    <FlexibleNavbarBox title="Clash Configs Manager">
      <TailwindcssNavbar
        linkGroups={navbarItems}
        selected={route.replace("[pid]", pid as string)}
        title="Clash Configs Manager"
      />
    </FlexibleNavbarBox>
  );

  const footer = <SimpleTextFooter>annogoo © 2022</SimpleTextFooter>;

  return (
    <>
      <Head>
        <title>Clash Configs Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <NavFooterLayout
        navbar={navbar}
        footer={footer}
        navbarClassName="bg-white"
        contentClassName="bg-white"
      >
        {children}
      </NavFooterLayout>
    </>
  );
};
