import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { Input, Button } from "@mantine/core";
import { IconKey, IconThumbUp } from "@tabler/icons";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Clash Configs Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <main className={styles.main}>
        <div className="flex flex-col sm:flex-row gap-2">
          <Input
            icon={<IconKey size={16} />}
            placeholder="设置或输入您的密钥"
            rightSection={
              <Button size="xs" variant="light">
                生成 UUID
              </Button>
            }
            rightSectionWidth={94}
          />
          <Button leftIcon={<IconThumbUp />}>进入 Clash 配置管理</Button>
        </div>
      </main>
    </div>
  );
};

export default Home;
