import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { Input } from '@mantine/core'
import { IconKey } from '@tabler/icons'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Clash Configs Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <main className={styles.main}>
        <Input icon={<IconKey size={16} />} placeholder="设置或输入您的密钥"/>
      </main>
    </div>
  )
}

export default Home
